### ISSUE TITLE
Make APK available?

### ISSUE THREAD

**Issue by kikura** [CitizenOneX/colmi_r06_fbp#1]
Would love to try this but don't see an app file in the release section.

**Comment by CitizenOneX** [comment]
Just to be clear, this is example code for communicating with a COLMi ring from a custom app, and not meant to be any standalone app that you might use for health tracking/step counting etc. 

To see debug logging you'd want to deploy this to your device from an IDE such as VS Code - but I have put a pre-built APK in the [Releases section](../releases) now if you wanted to try to deploy it on an Android device. Cheers

**Comment by kikura** [comment]
Many thanks.
